coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_head: false     # default true
  require_base: false



ignore:
  - "test/**"
  - "**/constants"
  - "**/domain"
  - "**/exceptions"
  - "**/dto"
  - "**/features"
