coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
comment:
  layout: "header, diff, changes,flags, files, sunburst, footer"


ignore:
  - "test/**"
  - "**/constants"
  - "**/domain"
  - "**/exceptions"
  - "**/dto"
