// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-n_Stc2LpbUtARhJXj2b5o6TRe6KSH6E',
    appId: '1:485760010856:web:5f67b26d52e13be0bac9dd',
    messagingSenderId: '485760010856',
    projectId: 'expense-tracking-831cf',
    authDomain: 'expense-tracking-831cf.firebaseapp.com',
    storageBucket: 'expense-tracking-831cf.firebasestorage.app',
    measurementId: 'G-12KGGDP5W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjWCSBQP4jZ7MczzCQkjjbbQQcd64iets',
    appId: '1:485760010856:android:30365b1c80058b32bac9dd',
    messagingSenderId: '485760010856',
    projectId: 'expense-tracking-831cf',
    storageBucket: 'expense-tracking-831cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZ1UptjUGePYIrkY3YoLWhT-01xil2uo',
    appId: '1:485760010856:ios:0232091014fa4575bac9dd',
    messagingSenderId: '485760010856',
    projectId: 'expense-tracking-831cf',
    storageBucket: 'expense-tracking-831cf.firebasestorage.app',
    iosBundleId: 'com.htilssu.expenseTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-n_Stc2LpbUtARhJXj2b5o6TRe6KSH6E',
    appId: '1:485760010856:web:3cfac2367b467fdebac9dd',
    messagingSenderId: '485760010856',
    projectId: 'expense-tracking-831cf',
    authDomain: 'expense-tracking-831cf.firebaseapp.com',
    storageBucket: 'expense-tracking-831cf.firebasestorage.app',
    measurementId: 'G-XB9B6B8R6T',
  );
}
