name: Build
on:
  workflow_call:

jobs:
  Build-APK:
    needs:
      - Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '22'
          cache: 'gradle'
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        id: dependency-cache
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-dependency-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-dependency-

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk