name: Testing
on:
  pull_request:
    branches:
      - "**/*"
  workflow_call:
  push:
    branches:
      - "**/*"

permissions:
  contents: write

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        id: dependency-cache
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-dependency-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-dependency-

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Lint code
        run: dart fix --apply
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git checkout ${{github.head_ref}} 
          git add .
          git commit -m "Apply dart fix"

      - name: Github Pushy
        uses: htilssu/github_push_action@v0

  Testing:
    needs:
      - Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        id: dependency-cache
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-dependency-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-dependency-

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          name: codecov-umbrella
          fail_ci_if_error: true
